--1. TÌM THÔNG TIN KHÁCH HÀNG MUA LOẠI SÁCH 'TÌNH CẢM'
SELECT * 
FROM [dbo].[KHACHHANG] 
WHERE KH.MAKH IN (
	SELECT MAKH
	FROM HOADON
	WHERE MAHD IN (
		SELECT MAHD
		FROM CHITIETHOADON
		WHERE MASACH IN (
			SELECT MASACH
			FROM SACH
			WHERE MALOAISACH IN(
				SELECT MALOAISACH
				FROM LOAISACH
				WHERE TENLOAISACH = N'TÌNH CẢM'
				)
			)
		)
	)

--2. TÌM THÔNG TIN NHÂN VIÊN THANH TOÁN SÁCH 'TÂM LÍ'
SELECT *
FROM [dbo].[NHANVIEN]
WHERE MANV IN(
	SELECT MANV 
	FROM [dbo].[HOADON]
	WHERE MAHD IN (
		SELECT MAHD
		FROM CHITIETHOADON
		WHERE MASACH IN (
			SELECT MASACH
			FROM SACH
			WHERE MALOAISACH IN(
				SELECT MALOAISACH
				FROM LOAISACH
				WHERE TENLOAISACH = N'TÂM LÍ'
				)
			)
		)
	)

--3. TÌM NHỮNG CUỐN SÁCH ĐƯỢC MUA VÀO THÁNG 5
SELECT *
FROM [dbo].[SACH]
WHERE MASACH IN (
	SELECT MASACH 
	FROM CHITIETHOADON
	WHERE MAHD IN (
		SELECT MAHD
		FROM HOADON
		WHERE MONTH(NGAYMUA) = 5
		)
	)
--4. TÌM SỐ LƯỢNG NHỮNG CUỐN SÁCH ĐƯỢC MUA VÀO THÁNG 5
SELECT TENSACH, CTHD.[SOLUONG]
FROM [dbo].[SACH],[dbo].[CHITIETHOADON] AS CTHD
WHERE [dbo].[SACH].MASACH = CTHD.MASACH AND CTHD.MAHD IN (
	SELECT MAHD
	FROM HOADON
	WHERE MONTH(NGAYMUA) = 5
	)

--5. TÌM THÔNG TIN TÁC GIẢ VIẾT NHỮNG LOẠI SÁCH 'VIỄN TƯỞNG'
SELECT *
FROM TACGIA
WHERE MATACGIA IN (
	SELECT MATACGIA
	FROM SACH_TACGIA
	WHERE MASACH IN (
		SELECT MASACH
		FROM SACH
		WHERE MALOAISACH IN (
			SELECT MALOAISACH
			FROM LOAISACH 
			WHERE TENLOAISACH = N'VIỄN TƯỞNG'
			)
		)
	)
--6. TÌM KIẾM KHÁCH HÀNG ĐÃ HỦY MUA SÁCH
SELECT *
FROM KHACHHANG
WHERE MAKH IN (
	SELECT MAKH
	FROM [dbo].[HOADON]
	WHERE TINHTRANG = N'ĐÃ HỦY'
	)
--7. TÌM KHÁCH HÀNG NỮ MUA LOẠI SÁCH 'VĂN HỌC'
SELECT *
FROM KHACHHANG
WHERE GIOITINH = N'NỮ' AND MAKH IN (
	SELECT MAKH
	FROM HOADON
	WHERE MAHD IN (
		SELECT MAHD 
		FROM CHITIETHOADON
		WHERE MASACH IN (
			SELECT MASACH 
			FROM SACH
			WHERE MALOAISACH IN (
				SELECT MALOAISACH
				FROM LOAISACH
				WHERE TENLOAISACH = N'VĂN HỌC'
				)
			)
		)
	)
--8. TÌM KHÁCH HÀNG NAM MUA LOẠI SÁCH 'Truyện Tranh' MUA TẠI THÁNG 5
SELECT *
FROM KHACHHANG
WHERE GIOITINH = N'NAM' AND MAKH IN (
	SELECT MAKH
	FROM HOADON
	WHERE MONTH(NGAYMUA) = 5 AND MAHD IN (
		SELECT MAHD 
		FROM CHITIETHOADON
		WHERE MASACH IN (
			SELECT MASACH 
			FROM SACH
			WHERE MALOAISACH IN (
				SELECT MALOAISACH
				FROM LOAISACH
				WHERE TENLOAISACH = N'VĂN HỌC' 
				)
			)
		)
	)
